  deploy:
    name: Deploy to SFTP
    needs: [lint-php, phpcs_check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v4
      - name: Deploy to SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server-dir: ${{ secrets.SFTP_REMOTE_DIR }}
          local-dir: ./boilerplate/
          protocol: sftp
